package com.gorkem.hrms.MernisService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.5.0
//
// Created by Quasar Development 
//
//----------------------------------------------------

public class INLFunctions
{
    public interface IFunc< Res>
    {
        Res Func() throws java.lang.Exception;
    }

    public interface IFunc1< T,Res>
    {
        Res Func(T p);
    }

    public interface IFunc2< T1,T2,Res>
    {
        Res Func(T1 p1,T2 p2);
    }

    public interface IAction
    {
        void Action();
    }

    public interface IAction1< T>
    {
        void Action(T p1);
    }
}

