package com.gorkem.hrms.MernisService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.5.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface INLIServiceEvents
{
    void Starting();
    void Completed(INLOperationResult result);
}
