package com.gorkem.hrms.MernisService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.5.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class INLOperationResult< T>
{
    
    public java.lang.Exception Exception;
    
    public T Result;
    
    public java.lang.Object Tag;
    
    public java.lang.String MethodName;
}
