CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(256) NOT NULL,
	password_hash character varying(512) NOT NULL,
    password_salt character varying(512) NOT NULL,    
    created_at_date date NOT NULL,
    updated_at_date date NOT NULL,
	is_active boolean NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE public.central_unit_users
(
    id integer NOT NULL,
    gender "char" NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    CONSTRAINT central_unit_users_pk PRIMARY KEY (id),
	CONSTRAINT central_unit_users_fk FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.corporate_users
(
    id integer NOT NULL,
    company_name character varying(256) NOT NULL,
    web_site character varying(256) NOT NULL,
    approve_status boolean NOT NULL,
    CONSTRAINT corporate_users_pk PRIMARY KEY (id),
	CONSTRAINT corporate_users_fk FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE
	
);

CREATE TABLE public.individual_users
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    identity_number character varying(11) NOT NULL,
	gender "char" NOT NULL,
    date_of_birth date NOT NULL,
	CONSTRAINT individual_users_pk PRIMARY KEY (id),
	CONSTRAINT individual_users_fk FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.occupations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(250) NOT NULL,
	description character varying(500) NOT NULL,
    updated_at date,
    added_at date,
	is_active boolean NOT NULL,
    CONSTRAINT occupations_pk PRIMARY KEY (id)
	
);

CREATE TABLE public.tokens
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    token_description character varying(512) NOT NULL,
    CONSTRAINT tokens_pk PRIMARY KEY (id)
);

CREATE TABLE public.user_tokens
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    token_id integer NOT NULL,
    CONSTRAINT user_tokens_pk PRIMARY KEY (id),
	CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,
	CONSTRAINT token_id_fk FOREIGN KEY (token_id) REFERENCES public.tokens (id) ON DELETE CASCADE
);


